"""
Constants and default values for the OEECF (Open Epidemiological-Economic Coupling Framework)
"""

# Default Economic Baseline Values
DEFAULT_PARTICIPATION_RATE = 0.65
DEFAULT_REMOTE_CAPACITY = 0.35
DEFAULT_REMOTE_EFFICIENCY = 0.80

# Sickness and Hospitalization Assumptions
SICK_AWAY_FRACTION = 0.90
SICK_PRODUCTIVITY_FACTOR = 0.10
QUARANTINE_PRODUCTIVITY_FACTOR = 0.50
HOSPITALIZATION_PRODUCTIVITY_FACTOR = 0.0

# Capacity Dynamics
DEFAULT_HOSPITAL_CAPACITY = 0.05
DEFAULT_BASE_FATALITY_RATE = 0.02
OVERFLOW_FATALITY_MULTIPLIER = 3.0

# Demand Shocks
DEFAULT_FEAR_FACTOR = 0.5
QUARANTINE_DEMAND_DROP = 0.8
MINIMUM_SUBSISTENCE_DEMAND = 0.2
